version: "3"
services:
    schema_registry:
        image: node:alpine
        volumes:
            - ./:/app
        working_dir: /app/schema_registry
        depends_on:
            - mongo
        environment:
            NODE_ENV: development
        ports:
            - 3084:3084
        command: npm run dev
    graphql:
        image: node:alpine
        volumes:
            - ./graphql:/app
        working_dir: /app
        depends_on:
            - mongo
        environment:
            NODE_ENV: development
        ports:
            - 3085:3085
        command: > 
            sh -c "npm run dev:default && tail -F anything"
            # sh -c "npm run dev && tail -F anything"
    mongo:
        image: mongo
        expose:
            - 27017
        ports:
            - 27017:27017            
        volumes:
            - ./data/db:/data/db